sudo apt install -y vitalium \
zynaddsubfx \
zynaddsubfx-dssi \
zynaddsubfx-lv2 \
zynaddsubfx-vst \
wah-plugins \
swh-lv2 \
swankyamp \
swankyamp-lv2 \
swankyamp-vst \
sorcer \
yoshimi \
carla \
carla-lv2 \
helm \
airwindows \
cardinal \
cardinal-lv2 \
cardinal-vst2 \
cardinal-vst3 \
phasex \
lmms \
adlplug \
ams \
amsynth \
ardour \
drumkv1-lv2 \
fomp \
hydrogen \
padthv1-lv2 \
zam-plugins \
wolf-spectrum \
wolf-shaper \
teragonaudio-plugins \
temper \
shiro-plugins \
tal-plugins \
pizmidi-plugins \
pitcheddelay \
oxefmsynth \
obxd \
mda-lv2 \
luftikus \
lufsmeter \
linuxsampler-vst \
juced-plugins \
klangfalter \
juce-opl \
jackass \
hybridreverb2 \
easyssp \
drumgizmo \
drowaudio-plugins \
dpf-plugins \
dpf-plugins-common \
dpf-plugins-dssi \
dpf-plugins-lv2 \
dpf-plugins-vst \
distrho-plugin-ports \
dexed arctican-plugins \
vocproc \
tap-lv2 \
synthv1 \
synthv1-lv2 \
zlfo \
so-synth-lv2 \
sherlock.lv2 \
samplv1 \
samplv1-lv2 \
rubberband-ladspa \
rubberband-lv2 \
noise-repellent \
moony.lv2 \
mod-pitchshifter \
mod-distortion \
melmatcheq.lv2 \
lv2vocoder \
kxstudio-recommended-audio-plugins-lv2 \
infamous-plugins \
gxvoxtonebender \
gxplugins \
guitarix \
geonkick \
eq10q \
drmr \
caps-lv2 \
calf-plugins \
calf-ladspa \
bshapr \
bsequencer \
blop-lv2 \
bjumblr \
beatslash-lv2 \
abgate \
fabla \
wolpertinger \
iem-plugin-suite-vst \
cv-lfo-blender-lv2 \
dragonfly-reverb-lv2 \
dragonfly-reverb-vst \
invada-studio-plugins-ladspa \
invada-studio-plugins-lv2 \
ir.lv2 \
amb-plugins \
autotalent \
blepvco \
blop \
blop-lv2 \
bs2b-ladspa \
cmt \
csladspa \
fil-plugins \
mcp-plugins \
omins \
rev-plugins \
ste-plugins \
swh-plugins \
tap-plugins \
vco-plugins \
vlevel \
a2jmidid \
gmidimonitor \
jack-keyboard \
jackd \
jackd2 \
japa \
jconvolver \
jkmeter \
jmeters \
jnoise \
klick \
meterbridge \
qjackctl \
qjackrcd \
qmidiarp \
qtractor \
radium-compressor \
rotter \
fst-dev \
foo-yc20 \
freewheeling \
horgand \
muse \
nama \
gxtuner \
sox \
sweep \
terminatorx
sudo apt install -y avldrums.lv2 avldrums.lv2-soundfont
sudo dpkg -i --force-overwrite /var/cache/apt/archives/avldrums.lv2-soundfont*.deb
